---
title: "Untitled"
output: html_document
date: "2023-06-26"
---

# Data Prep

```{r Load Packages, Define Directories}
packages <- c(
  "tidycensus", "tidyverse", "here", "tigris", "svDialogs", "tmap", "sf", "leaflet")

# load and install required packages
package.check <- lapply(
  packages,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE, quietly = TRUE)
      library(x, character.only = TRUE)
    }
  }
)

path <- c(
    "dscr" = here("data", "scratch"),
    "drpriv" = here("data", "raw", "private"),
    "ddpub" = here("data", "derived", "public"),
    "ddpriv" = here("data", "derived", "private"),
    "rfig" = here("results", "figures"),
    "roth" = here("results", "other"),
    "rtab" = here("results", "tables")
)

```


```{r Record variable names}
# Record raw variable names for Spielman et al's data and our own
acs_variables = list(
   "B01002_001E", # median age
    "B03002_001E", # total population (demoninator for race)
    "B03002_004E", # total black
    "B03002_005E", # total native american
    "B03002_006E", # total asian
    "B03002_012E", # total latinx
    "B06001_002E", # total under 5
    "B09020_001E", # total above 65 -- they got from different section than under 5. Try summing B06001_011E + B06001_012E and see if result is equivalent?
    "B01003_001E", # total population (denominator for age, sex) -- check if this is the best denominator for age
    "B25008_001E", # total population in occupied housing units?
    "B25002_002E", # total occupied housing units? Believe they divide B25008_001E/B25002_002E to get people per 
    "B25003_003E", # total renter occupied housing units?
    "B25002_001E", # total housing units for which occupancy status is known?
    "B09020_021E", # total 65+ living in group quarters
    "B01001_026E", # total female
    "B11001_006E", # total female-headed family households
    "B11001_001E", # total households (denominator for pct female-headed)
    "B25002_003E", # total vacant housing units?
    "B19025_001E", # aggregate household income
    "B16004_029E", # total speak spanish, speak english not well ages 18-64
    "B16004_030E", # total speak spanish, speak english not at all ages 18-64
    "B16004_034E", # total speak other indo-european languages, speak english not well ages 18-64
    "B16004_035E", # total speak other indo-european languages, speak english not at all ages 18-64
    "B16004_039E", # total speak asian languages, speak english not well ages 18-64
    "B16004_040E", # total speak asian languages, speak english not at all ages 18-64
    "B16004_044E", # total speak other languages, speak english not well ages 18-64
    "B16004_045E", # total speak other languages, speak english not at all ages 18-64
    "B16004_051E", # total speak spanish, speak english not well ages 65+
    "B16004_052E", # total speak spanish, speak english not at all ages 65+
    "B16004_056E", # total speak other indo-european languages, speak english not well ages 65+
    "B16004_057E", # total speak other indo-european languages, speak english not at all ages 65+
    "B16004_061E", # total speak asian languages, speak english not well ages 65+
    "B16004_062E", # total speak asian languages, speak english not at all ages 65+
    "B16004_066E", # total speak other languages, speak english not well ages 65+
    "B16004_067E", # total speak other languages, speak english not at all ages 65+
    "B16004_024E", # total ages 18-64 for language category
    "B16004_046E", # total 65+ for language category
    "B16004_025E", # total ages 18-64 that speak only english
    "B16004_047E", # total 65+ that speak only english
    "B23022_025E", # total male unemployed for last 12 months -- did they not have the stat available without the male/female cross tabulation?
    "B23022_049E", # total female unemployed for last 12 months
    "B23022_001E", # total for unemployment by sex stats
    "B17021_002E", # total pop below poverty level
    "B17021_001E", # total pop for which poverty info available (denominator for poverty pct)
    "B25024_010E", # number of mobile home housing units in structure
    "B25024_001E", # total units in structure
    "B15002_003E", # total male no schooling completed
    "B15002_004E", # total male nursery to 4th grade
    "B15002_005E", # total male 5th and 6th grade
    "B15002_006E", # total male 7th and 8th grade
    "B15002_007E", # total male 9th grade
    "B15002_008E", # total male 10th grade
    "B15002_009E", # total male 11th grade
    "B15002_010E", # total male 12th grade, no diploma
    "B15002_020E", # total female no schooling completed
    "B15002_021E", # total female nursery to 4th grade
    "B15002_022E", # total female 5th and 6th grade
    "B15002_023E", # total female 7th and 8th grade
    "B15002_024E", # total female 9th grade
    "B15002_025E", # total female 10th grade
    "B15002_026E", # total female 11th grade
    "B15002_027E", # total female 12th grade, no diploma
    "B15002_001E", # total sex by educational attainment (denominator for education)
    "C24010_038E", # total female employed
    "C24010_001E", # total for which sex and occupation -- including employment status -- known (a denominator)
    "C24030_003E", # total male extractive industries
    "C24030_030E", # total female extractive industries
    "C24030_001E", # total for which sex and industry known
    "C24010_019E", # total male in service occupations
    "C24010_055E", # total female in service occupations
    "B19055_002E", # total households(?) with social security income
    "B19055_001E", # total households(?) for which social security income status known
    "B25044_003E", # total owner occupied no vehicle available
    "B25044_010E", # total rental occupied no vehicle available
    "B25044_001E", # total for which tenure by vehicle available known
    "B09002_002E", # total children in married couple families
    "B09002_001E", # total children by family type and age (a denominator)
    "B19001_017E", # total households over 200k income
    "B11001_001E", # total households (denominator -- is there an alternative from same category? B19001_001E?)
    "B06007_005E", # total speak spanish, speak english less than very well
    "B06007_008E", # total speak another language, speak english less than very well
    "B06007_001E", # total speak another language (a denominator)
    "B16010_002E", # total less than high school
    "B16010_001E", # total for which education, employment, language at home known (a denominator)
    "C24050_002E", # total in extractive industries
    "C24050_001E", # total for which industry known (a denominator)
    "C24050_029E", # total in service occupations
    "B08201_002E", # total households no vehicle available
    "B08201_001E", # total households for which vehicle status and family size known (a denominator)
    "B25064_001E", # median gross rent
    "B25077_001E"
)
    
spielman_acs_variables = list(
    "ACS12_5yr_B01002001", # median age
    "ACS12_5yr_B03002001", # total population (demoninator for race)
    "ACS12_5yr_B03002004", # total black
    "ACS12_5yr_B03002005", # total native american
    "ACS12_5yr_B03002006", # total asian
    "ACS12_5yr_B03002012", # total latinx
    "ACS12_5yr_B06001002", # total under 5 
    "ACS12_5yr_B09020001", # total above 65 -- they got from different section than under 5. Try summing B06001_011E + B06001_012E and see if result is equivalent?
    "ACS12_5yr_B01003001", # total population (denominator for age, sex) -- check if this is the best denominator for age
    "ACS12_5yr_B25008001", # total population in occupied housing units?
    "ACS12_5yr_B25002002", # total occupied housing units? Believe they divide B25008_001E/B25002_002E to get people per 
    "ACS12_5yr_B25003003", # total renter occupied housing units?
    "ACS12_5yr_B25002001", # total housing units for which occupancy status is known?
    "ACS12_5yr_B09020021", # total 65+ living in group quarters
    "ACS12_5yr_B01001026", # total female
    "ACS12_5yr_B11001006", # total female-headed family households
    "ACS12_5yr_B11001001", # total households (denominator for pct female-headed)
    "ACS12_5yr_B25002003", # total vacant housing units?
    "ACS12_5yr_B19025001", # aggregate household income
    "ACS12_5yr_B16004029", # total speak spanish, speak english not well ages 18-64
    "ACS12_5yr_B16004030", # total speak spanish, speak english not at all ages 18-64
    "ACS12_5yr_B16004034", # total speak other indo-european languages, speak english not well ages 18-64
    "ACS12_5yr_B16004035", # total speak other indo-european languages, speak english not at all ages 18-64
    "ACS12_5yr_B16004039", # total speak asian languages, speak english not well ages 18-64
    "ACS12_5yr_B16004040", # total speak asian languages, speak english not at all ages 18-64
    "ACS12_5yr_B16004044", # total speak other languages, speak english not well ages 18-64
    "ACS12_5yr_B16004045", # total speak other languages, speak english not at all ages 18-64
    "ACS12_5yr_B16004051", # total speak spanish, speak english not well ages 65+
    "ACS12_5yr_B16004052", # total speak spanish, speak english not at all ages 65+
    "ACS12_5yr_B16004056", # total speak other indo-european languages, speak english not well ages 65+
    "ACS12_5yr_B16004057", # total speak other indo-european languages, speak english not at all ages 65+
    "ACS12_5yr_B16004061", # total speak asian languages, speak english not well ages 65+
    "ACS12_5yr_B16004062", # total speak asian languages, speak english not at all ages 65+
    "ACS12_5yr_B16004066", # total speak other languages, speak english not well ages 65+
    "ACS12_5yr_B16004067", # total speak other languages, speak english not at all ages 65+
    "ACS12_5yr_B16004024", # total ages 18-64 for language category
    "ACS12_5yr_B16004046", # total 65+ for language category
    "ACS12_5yr_B16004025", # total ages 18-64 that speak only english
    "ACS12_5yr_B16004047", # total 65+ that speak only english
    "ACS12_5yr_B23022025", # total male unemployed for last 12 months -- did they not have the stat available without the male/female cross tabulation?
    "ACS12_5yr_B23022049", # total female unemployed for last 12 months
    "ACS12_5yr_B23022001", # total for unemployment by sex stats
    "ACS12_5yr_B17021002", # total pop below poverty level
    "ACS12_5yr_B17021001", # total pop for which poverty info available (denominator for poverty pct)
    "ACS12_5yr_B25024010", # number of mobile home housing units in structure
    "ACS12_5yr_B25024001", # total units in structure
    "ACS12_5yr_B15002003", # total male no schooling completed
    "ACS12_5yr_B15002004", # total male nursery to 4th grade
    "ACS12_5yr_B15002005", # total male 5th and 6th grade
    "ACS12_5yr_B15002006", # total male 7th and 8th grade
    "ACS12_5yr_B15002007", # total male 9th grade
    "ACS12_5yr_B15002008", # total male 10th grade
    "ACS12_5yr_B15002009", # total male 11th grade
    "ACS12_5yr_B15002010", # total male 12th grade, no diploma
    "ACS12_5yr_B15002020", # total female no schooling completed
    "ACS12_5yr_B15002021", # total female nursery to 4th grade
    "ACS12_5yr_B15002022", # total female 5th and 6th grade
    "ACS12_5yr_B15002023", # total female 7th and 8th grade
    "ACS12_5yr_B15002024", # total female 9th grade
    "ACS12_5yr_B15002025", # total female 10th grade
    "ACS12_5yr_B15002026", # total female 11th grade
    "ACS12_5yr_B15002027", # total female 12th grade, no diploma
    "ACS12_5yr_B15002001", # total sex by educational attainment (denominator for education)
    "ACS12_5yr_C24010038", # total female employed
    "ACS12_5yr_C24010001", # total for which sex and occupation -- including employment status -- known (a denominator)
    "ACS12_5yr_C24030003", # total male extractive industries
    "ACS12_5yr_C24030030", # total female extractive industries
    "ACS12_5yr_C24030001", # total for which sex and industry known
    "ACS12_5yr_C24010019", # total male in service occupations
    "ACS12_5yr_C24010055", # total female in service occupations
    "ACS12_5yr_B19055002", # total households(?) with social security income
    "ACS12_5yr_B19055001", # total households(?) for which social security income status known
    "ACS12_5yr_B25044003", # total owner occupied no vehicle available
    "ACS12_5yr_B25044010", # total rental occupied no vehicle available
    "ACS12_5yr_B25044001", # total for which tenure by vehicle available known
    "ACS12_5yr_B09002002", # total children in married couple families
    "ACS12_5yr_B09002001", # total children by family type and age (a denominator)
    "ACS12_5yr_B19001017", # total households over 200k income
    "ACS12_5yr_B11001001", # total households (denominator -- is there an alternative from same category? B19001_001E?)
    "ACS12_5yr_B06007005", # total speak spanish, speak english less than very well
    "ACS12_5yr_B06007008", # total speak another language, speak english less than very well
    "ACS12_5yr_B06007001", # total speak another language (a denominator)
    "ACS12_5yr_B16010002", # total less than high school
    "ACS12_5yr_B16010001", # total for which education, employment, language at home known (a denominator)
    "ACS12_5yr_C24050002", # total in extractive industries
    "ACS12_5yr_C24050001", # total for which industry known (a denominator)
    "ACS12_5yr_C24050029", # total in service occupations
    "ACS12_5yr_B08201002", # total households no vehicle available
    "ACS12_5yr_B08201001", # total households for which vehicle status and family size known (a denominator)
    "ACS12_5yr_B25064001", # median gross rent
    "ACS12_5yr_B25077001" # median value (of what? housing?)
)
    
# *looks like they calculate some things in a slightly slower way and then recalculate them with fewer vars
```

```{r}
census_api_key(
  dlgInput(
    "Enter a Census API Key",
    Sys.getenv("CENSUS_API_KEY")
  )$res,
  overwrite = TRUE
)
```

```{r Save ACS Metadata}
vars_2012 <- load_variables(2012, 'acs5')
saveRDS(vars_2012, here("data", "metadata", "acs_vars.RDS"))
```

```{r Pull in Census Data}
counties <- get_acs(
  geography = "county", 
  variables = acs_variables,
  year = 2012,
  geometry = TRUE, 
  survey = "acs5",
  output = "wide"
)
```
```{r}
counties <- counties %>%
  mutate(GEOID_num = as.numeric(GEOID)) %>%
  filter(GEOID_num < 72000)
```

```{r}
pal <- colorNumeric(palette = "YlGnBu",
                    domain = counties$B01002_001E)

counties %>%
  st_transform(4326) %>%
  leaflet() %>% #creates blank leaflet map
  setView(lng = -98, lat = 38, zoom = 4) %>% #tells us how far to zoom in/where our map should show us. lower zoom numbers means more zoomed out
  addTiles() %>% #adds base layer of world!
  addPolygons(weight = 0.2, #weight controls thickness of polygon outline
              fillColor = ~pal(B01002_001E),
              fillOpacity = .8,
              popup = labs) %>%
  addLegend(pal = pal,
            values = ~B01002_001E,
            title = "Median Age")
  
```

STILL NEED TO FIND A LAND AREA FIELD


```{r Import Spielman Data}
# Base ACS data
acs <- read_csv(here( path["drpub"], 'sovi_acs.csv'), skip = 1 )

# Decennial supplemental
dec_sup1 <- read_csv(here(path["drpub"],'sovi_decennial_sup1.csv'))

# ACS supplemental
acs_sup2 <- read_csv(here(path["drpub"], 'sovi_acs_kids.csv'))

# Drop Puerto Rico
acs <- acs %>%
  filter(Geo_STATE != "72")
```
maybe join all at once, doing a join across all of the relevant datasets

```{r}
path["drpub"]
```




